# This script will run only when the `prod` profile is active.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springframework_prod
    username: root
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false